services:
  - type: web
    name: mag-obyava-backend
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        prompt: true
      - key: TELEGRAM_CHANNEL_ID
        prompt: true
      - key: ADMIN_TELEGRAM_ID
        prompt: true
      - key: SUPABASE_URL
        prompt: true
      - key: SUPABASE_KEY
        prompt: true
      - key: PUBLIC_ORIGIN
        value: "https://demiurg-guru.github.io/mag-obyava"
